import { getPrismaClient } from "../src/client.js";
import {
  AvailabilityModel,
  BillingModel,
  CommerceDomain,
  DigitalDeliveryMethod,
  InventoryAvailability,
  MerchantStatus,
  ProductKind,
  ServiceDeliveryMode,
} from "../src/generated/prisma/enums.js";
import type { Prisma } from "../src/generated/prisma/client.js";

const categoryIds = {
  retail: "retail_goods",
  apparel: "retail_goods.apparel",
  shoes: "retail_goods.apparel.shoes",
  electronics: "retail_goods.electronics",
  smartphones: "retail_goods.electronics.smartphones",
  laptops: "retail_goods.electronics.laptops",
  audio: "retail_goods.electronics.audio",
  homeAppliances: "retail_goods.electronics.home_appliances",
  electronicsAccessories: "retail_goods.electronics.accessories",
  booksMedia: "retail_goods.books_media",
  books: "retail_goods.books_media.books",
  foodBeverage: "retail_goods.food_beverage",
  restaurantMeals: "retail_goods.food_beverage.restaurant_meals",
  services: "services_subscriptions",
  digitalProducts: "services_subscriptions.digital_products",
  software: "services_subscriptions.software",
  saas: "services_subscriptions.software.saas",
  memberships: "services_subscriptions.memberships",
  professionalServices: "services_subscriptions.professional_services",
  bookings: "bookings",
  transportation: "bookings.transportation",
  flights: "bookings.transportation.flights",
  accommodation: "bookings.accommodation",
  hotels: "bookings.accommodation.hotels",
  activities: "bookings.activities",
} as const;

type CategorySeed = readonly [
  id: string,
  parentId: string | null,
  domain: CommerceDomain,
  kind: ProductKind,
  name: string,
  aliases: string[],
  billing: BillingModel,
  availability: AvailabilityModel,
];

const categorySeeds: CategorySeed[] = [
  [
    categoryIds.retail,
    null,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Retail Goods",
    ["physical goods", "online shopping"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.apparel,
    categoryIds.retail,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Apparel",
    ["clothing"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.shoes,
    categoryIds.apparel,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Shoes",
    ["footwear", "sneakers"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.electronics,
    categoryIds.retail,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Electronics",
    ["consumer electronics"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.smartphones,
    categoryIds.electronics,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Smartphones",
    ["mobile phones", "phones"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.laptops,
    categoryIds.electronics,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Laptops",
    ["notebooks", "computers"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.audio,
    categoryIds.electronics,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Audio",
    ["headphones", "earbuds", "speakers"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.homeAppliances,
    categoryIds.electronics,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Home Appliances",
    ["appliances", "kitchen appliances"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.electronicsAccessories,
    categoryIds.electronics,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Electronics Accessories",
    ["accessories", "chargers", "cables"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.booksMedia,
    categoryIds.retail,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Books & Media",
    ["media"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.books,
    categoryIds.booksMedia,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Books",
    ["printed books"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.foodBeverage,
    categoryIds.retail,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Food & Beverage",
    ["food", "meals"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.restaurantMeals,
    categoryIds.foodBeverage,
    CommerceDomain.RETAIL_GOODS,
    ProductKind.PHYSICAL_GOOD,
    "Restaurant Meals",
    ["food delivery", "prepared food"],
    BillingModel.ONE_TIME,
    AvailabilityModel.STOCK,
  ],
  [
    categoryIds.services,
    null,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.SERVICE,
    "Services & Subscriptions",
    ["memberships", "subscriptions"],
    BillingModel.ONE_TIME,
    AvailabilityModel.UNLIMITED,
  ],
  [
    categoryIds.digitalProducts,
    categoryIds.services,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.DIGITAL_PRODUCT,
    "Digital Products",
    ["downloads", "digital goods"],
    BillingModel.ONE_TIME,
    AvailabilityModel.UNLIMITED,
  ],
  [
    categoryIds.software,
    categoryIds.services,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.DIGITAL_PRODUCT,
    "Software",
    ["applications"],
    BillingModel.RECURRING,
    AvailabilityModel.UNLIMITED,
  ],
  [
    categoryIds.saas,
    categoryIds.software,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.DIGITAL_PRODUCT,
    "SaaS",
    ["software subscriptions"],
    BillingModel.RECURRING,
    AvailabilityModel.UNLIMITED,
  ],
  [
    categoryIds.memberships,
    categoryIds.services,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.SERVICE,
    "Memberships",
    ["plans"],
    BillingModel.RECURRING,
    AvailabilityModel.UNLIMITED,
  ],
  [
    categoryIds.professionalServices,
    categoryIds.services,
    CommerceDomain.SERVICES_SUBSCRIPTIONS,
    ProductKind.SERVICE,
    "Professional Services",
    ["consulting", "coaching"],
    BillingModel.ONE_TIME,
    AvailabilityModel.TIME_SLOT,
  ],
  [
    categoryIds.bookings,
    null,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Bookings",
    ["travel", "reservations"],
    BillingModel.ONE_TIME,
    AvailabilityModel.CAPACITY,
  ],
  [
    categoryIds.transportation,
    categoryIds.bookings,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Transportation",
    ["transport"],
    BillingModel.ONE_TIME,
    AvailabilityModel.SEAT,
  ],
  [
    categoryIds.flights,
    categoryIds.transportation,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Flights",
    ["airline tickets", "air travel"],
    BillingModel.ONE_TIME,
    AvailabilityModel.SEAT,
  ],
  [
    categoryIds.accommodation,
    categoryIds.bookings,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Accommodation",
    ["lodging"],
    BillingModel.ONE_TIME,
    AvailabilityModel.CAPACITY,
  ],
  [
    categoryIds.hotels,
    categoryIds.accommodation,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Hotels",
    ["hotel accommodation"],
    BillingModel.ONE_TIME,
    AvailabilityModel.CAPACITY,
  ],
  [
    categoryIds.activities,
    categoryIds.bookings,
    CommerceDomain.BOOKINGS,
    ProductKind.BOOKING,
    "Activities",
    ["experiences", "tours"],
    BillingModel.ONE_TIME,
    AvailabilityModel.CAPACITY,
  ],
];

const categories: Prisma.CategoryCreateManyInput[] = categorySeeds.map(
  ([
    id,
    parentId,
    domain,
    productKind,
    name,
    aliases,
    defaultBillingModel,
    defaultAvailabilityModel,
  ]) => ({
    id,
    parentId,
    domain,
    productKind,
    slug: id.split(".").at(-1) ?? id,
    name,
    level: id.split(".").length - 1,
    aliases,
    defaultBillingModel,
    defaultAvailabilityModel,
  }),
);

type AttributeDefinition = {
  type: "string" | "number" | "boolean";
  scope: "product" | "variant";
  required?: boolean;
  filterable?: boolean;
  comparable?: boolean;
  aliases?: string[];
};

const field = (
  type: AttributeDefinition["type"],
  scope: AttributeDefinition["scope"],
  options: Omit<AttributeDefinition, "type" | "scope"> = {},
): AttributeDefinition => ({ type, scope, ...options });

const categorySchemas: Prisma.CategorySchemaCreateManyInput[] = [
  {
    id: "d1111111-1111-4111-8111-111111111111",
    categoryId: categoryIds.shoes,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", {
          required: true,
          filterable: true,
          aliases: ["product_type", "shoe_type"],
        }),
        sport: field("string", "product", { filterable: true }),
        material: field("string", "product", { filterable: true }),
        size: field("string", "variant", {
          required: true,
          filterable: true,
          comparable: true,
          aliases: ["shoe_size", "size_name"],
        }),
        color: field("string", "variant", {
          required: true,
          filterable: true,
          aliases: ["colour", "color_name"],
        }),
      },
    },
  },
  {
    id: "d2222222-2222-4222-8222-222222222222",
    categoryId: categoryIds.smartphones,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", {
          required: true,
          filterable: true,
        }),
        model: field("string", "product", { required: true, filterable: true }),
        operatingSystem: field("string", "product", {
          filterable: true,
          aliases: ["os"],
        }),
        storage: field("string", "variant", {
          required: true,
          filterable: true,
          comparable: true,
          aliases: ["capacity", "storage_size"],
        }),
        color: field("string", "variant", {
          required: true,
          filterable: true,
          aliases: ["colour", "color_name"],
        }),
      },
    },
  },
  {
    id: "d8888888-8888-4888-8888-888888888888",
    categoryId: categoryIds.laptops,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", { required: true, filterable: true }),
        useCase: field("string", "product", { filterable: true }),
        gpu: field("string", "variant", { filterable: true, comparable: true }),
        ramGb: field("number", "variant", { comparable: true }),
        storageGb: field("number", "variant", { comparable: true, aliases: ["storage"] }),
      },
    },
  },
  {
    id: "d9999999-9999-4999-9999-999999999999",
    categoryId: categoryIds.audio,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", { required: true, filterable: true }),
        noiseCancelling: field("boolean", "product", { filterable: true }),
        batteryLifeHours: field("number", "variant", { comparable: true }),
        color: field("string", "variant", { filterable: true, aliases: ["colour"] }),
      },
    },
  },
  {
    id: "daaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa",
    categoryId: categoryIds.homeAppliances,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", { required: true, filterable: true }),
        wattage: field("number", "variant", { comparable: true }),
        color: field("string", "variant", { filterable: true, aliases: ["colour"] }),
      },
    },
  },
  {
    id: "dbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
    categoryId: categoryIds.electronicsAccessories,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", { required: true, filterable: true }),
        compatibility: field("string", "product", { filterable: true }),
        color: field("string", "variant", { filterable: true, aliases: ["colour"] }),
      },
    },
  },
  {
    id: "d3333333-3333-4333-8333-333333333333",
    categoryId: categoryIds.digitalProducts,
    version: "1.0",
    attributeSchema: {
      attributes: {
        productType: field("string", "product", {
          required: true,
          filterable: true,
        }),
        language: field("string", "product", { filterable: true }),
        level: field("string", "product", { filterable: true }),
        license: field("string", "variant", {
          required: true,
          filterable: true,
        }),
      },
    },
  },
  {
    id: "d4444444-4444-4444-8444-444444444444",
    categoryId: categoryIds.professionalServices,
    version: "1.0",
    attributeSchema: {
      attributes: {
        serviceType: field("string", "product", {
          required: true,
          filterable: true,
        }),
        language: field("string", "product", { filterable: true }),
        mode: field("string", "variant", { required: true, filterable: true }),
        durationMinutes: field("number", "variant", {
          required: true,
          comparable: true,
          aliases: ["duration", "duration_minutes"],
        }),
      },
    },
  },
  {
    id: "d5555555-5555-4555-8555-555555555555",
    categoryId: categoryIds.activities,
    version: "1.0",
    attributeSchema: {
      attributes: {
        experienceType: field("string", "product", {
          required: true,
          filterable: true,
        }),
        destination: field("string", "product", {
          required: true,
          filterable: true,
        }),
        difficulty: field("string", "product", { filterable: true }),
        date: field("string", "variant", { required: true, filterable: true }),
        time: field("string", "variant", { required: true }),
      },
    },
  },
  {
    id: "d6666666-6666-4666-8666-666666666666",
    categoryId: categoryIds.restaurantMeals,
    version: "1.0",
    attributeSchema: {
      attributes: {
        cuisine: field("string", "product", {
          required: true,
          filterable: true,
        }),
        dietary: field("string", "product", { filterable: true }),
        portion: field("string", "variant", { filterable: true }),
        spiceLevel: field("string", "variant", {
          filterable: true,
          aliases: ["spice_level"],
        }),
      },
    },
  },
  {
    id: "d7777777-7777-4777-8777-777777777777",
    categoryId: categoryIds.saas,
    version: "1.0",
    attributeSchema: {
      attributes: {
        softwareType: field("string", "product", {
          required: true,
          filterable: true,
        }),
        billingInterval: field("string", "variant", {
          required: true,
          filterable: true,
          aliases: ["billing_cycle"],
        }),
        seats: field("number", "variant", { required: true, comparable: true }),
      },
    },
  },
];

const merchantIds = {
  sneakerHub: "11111111-1111-4111-8111-111111111111",
  kentRidgeSports: "22222222-2222-4222-8222-222222222222",
  digitalLearningLab: "33333333-3333-4333-8333-333333333333",
  careerStudio: "44444444-4444-4444-8444-444444444444",
  lionCityExperiences: "55555555-5555-4555-8555-555555555555",
  orchardTech: "66666666-6666-4666-8666-666666666666",
  // Electronics: NUS Gadget Hub sells across home appliances, mobile
  // electronics/audio, laptops, and accessories (a Challenger-style
  // generalist) — one of the required merchant profiles.
  nusGadgetHub: "bb111111-1111-4111-8111-111111111111",
  // Electronics: laptops + smartphones.
  circuitAndByte: "cc111111-1111-4111-8111-111111111111",
  // Electronics: a myriad/combination store weighted toward accessories.
  accessoryWorldSg: "dd111111-1111-4111-8111-111111111111",
  // Electronics: laptops only, budget-focused.
  campusComputeCo: "77777777-7777-4777-8777-777777777777",
  // Electronics: laptops only, workstation-class.
  studioHardwareSg: "88888888-8888-4888-8888-888888888888",
  // Electronics: laptops only, ties with Studio Hardware SG on spec+price.
  pixelWorksLabs: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  // Professional services: a broad generalist (career coaching, resume
  // writing, LinkedIn optimization, interview prep) — the Challenger-style
  // profile mirrored into the professional_services domain.
  careerLaunchCollective: "ee111111-1111-4111-8111-111111111111",
  // Professional services: bookkeeping only.
  ledgerlinePartners: "99999999-9999-4999-8999-999999999999",
  // Professional services: myriad/combination, weighted toward business-
  // admin add-ons (payroll, tax filing, notarization, bookkeeping).
  adminAndBeyond: "ff111111-1111-4111-8111-111111111111",
} as const;

const productIds = {
  sneakerHubGtCut3: "a1111111-1111-4111-8111-111111111111",
  kentRidgeGtCut3: "a2222222-2222-4222-8222-222222222222",
  analyticsStarterKit: "a3333333-3333-4333-8333-333333333333",
  careerCoaching: "a4444444-4444-4444-8444-444444444444",
  sentosaKayaking: "a5555555-5555-4555-8555-555555555555",
  iphone16Pro: "a6666666-6666-4666-8666-666666666666",
  // NUS Gadget Hub (generalist)
  gadgetHubBlender: "ab111111-1111-4111-8111-111111111111",
  gadgetHubEarbuds: "ab222222-2222-4222-8222-222222222222",
  gadgetHubLaptop: "ab333333-3333-4333-8333-333333333333",
  gadgetHubPowerBank: "ab444444-4444-4444-8444-444444444444",
  // Circuit & Byte (laptops + smartphones)
  circuitBytePro15: "ac111111-1111-4111-8111-111111111111",
  circuitBytePhoneX: "ac222222-2222-4222-8222-222222222222",
  // AccessoryWorld SG (myriad, accessories-heavy)
  accessoryWorldEarbuds: "ad111111-1111-4111-8111-111111111111",
  accessoryWorldPhoneCase: "ad222222-2222-4222-8222-222222222222",
  accessoryWorldCharger: "ad333333-3333-4333-8333-333333333333",
  accessoryWorldLaptopSleeve: "ad444444-4444-4444-8444-444444444444",
  // Laptop-only merchants (same ids as the earlier tim-fixtures seed — a
  // true migration/update in place, not a duplicate insert).
  creatorbook14: "b7777777-7777-4777-8777-777777777771",
  studioProX: "b8888888-8888-4888-8888-888888888881",
  renderBookPro: "baaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  // Career Launch Collective (professional services generalist)
  resumeWriting: "af111111-1111-4111-8111-111111111111",
  linkedinMakeover: "af222222-2222-4222-8222-222222222222",
  mockInterview: "af333333-3333-4333-8333-333333333333",
  // Campus Career Studio's second service (career coaching + resume review)
  resumeReviewPackage: "af444444-4444-4444-8444-444444444444",
  // Ledgerline Partners (same id as the earlier tim-fixtures seed)
  bookkeepingMonthly: "b9999999-9999-4999-8999-999999999991",
  // Admin & Beyond Services (myriad, admin-heavy)
  payrollProcessing: "af666666-6666-4666-8666-666666666666",
  taxFilingAssistance: "af777777-7777-4777-8777-777777777777",
  notarizationService: "af888888-8888-4888-8888-888888888888",
} as const;

const merchants: Prisma.MerchantCreateManyInput[] = [
  {
    id: merchantIds.sneakerHub,
    name: "NUS Sneaker Hub",
    category: categoryIds.shoes,
    description: "Basketball footwear with same-day campus delivery.",
    currency: "SGD",
    contactEmail: "sneakers@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.kentRidgeSports,
    name: "Kent Ridge Sports",
    category: categoryIds.shoes,
    description: "Campus sports equipment and footwear retailer.",
    currency: "SGD",
    contactEmail: "sports@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.digitalLearningLab,
    name: "NUS Digital Learning Lab",
    category: categoryIds.digitalProducts,
    description: "Downloadable learning resources for university students.",
    currency: "SGD",
    contactEmail: "digital@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.careerStudio,
    name: "Campus Career Studio",
    category: categoryIds.professionalServices,
    description: "Remote and in-person career development services.",
    currency: "SGD",
    contactEmail: "career@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.lionCityExperiences,
    name: "Lion City Experiences",
    category: categoryIds.activities,
    description: "Small-group activities and experiences around Singapore.",
    currency: "SGD",
    contactEmail: "experiences@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.orchardTech,
    name: "Orchard Tech",
    category: categoryIds.smartphones,
    description: "Consumer electronics with island-wide delivery.",
    currency: "SGD",
    contactEmail: "catalog@example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.nusGadgetHub,
    name: "NUS Gadget Hub",
    category: categoryIds.electronics,
    description: "One-stop electronics retailer: home appliances, mobile electronics, laptops, and accessories.",
    currency: "SGD",
    contactEmail: "sales@nusgadgethub.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.circuitAndByte,
    name: "Circuit & Byte",
    category: categoryIds.laptops,
    description: "Laptops and smartphones for campus life.",
    currency: "SGD",
    contactEmail: "hello@circuitandbyte.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.accessoryWorldSg,
    name: "AccessoryWorld SG",
    category: categoryIds.electronicsAccessories,
    description: "Phone, laptop, and audio accessories, plus a few essentials.",
    currency: "SGD",
    contactEmail: "support@accessoryworld.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.campusComputeCo,
    name: "Campus Compute Co",
    category: categoryIds.laptops,
    description: "Creator and gaming laptops with campus delivery.",
    currency: "SGD",
    contactEmail: "sales@campuscompute.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.studioHardwareSg,
    name: "Studio Hardware SG",
    category: categoryIds.laptops,
    description: "Workstation-class laptops for creative professionals.",
    currency: "SGD",
    contactEmail: "hello@studiohardware.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.pixelWorksLabs,
    name: "PixelWorks Labs",
    category: categoryIds.laptops,
    description: "Creator-focused workstation laptops.",
    currency: "SGD",
    contactEmail: "hello@pixelworkslabs.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.careerLaunchCollective,
    name: "Career Launch Collective",
    category: categoryIds.professionalServices,
    description: "Full-service career development: coaching, resumes, LinkedIn, interview prep.",
    currency: "SGD",
    contactEmail: "hello@careerlaunch.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.ledgerlinePartners,
    name: "Ledgerline Partners",
    category: categoryIds.professionalServices,
    description: "Small-business bookkeeping and accounting support.",
    currency: "SGD",
    contactEmail: "hello@ledgerline.example.com",
    status: MerchantStatus.ACTIVE,
  },
  {
    id: merchantIds.adminAndBeyond,
    name: "Admin & Beyond Services",
    category: categoryIds.professionalServices,
    description: "Business admin support: payroll, tax filing, notarization, and bookkeeping add-ons.",
    currency: "SGD",
    contactEmail: "hello@adminandbeyond.example.com",
    status: MerchantStatus.ACTIVE,
  },
];

const products: Prisma.ProductCreateManyInput[] = [
  {
    id: productIds.sneakerHubGtCut3,
    merchantId: merchantIds.sneakerHub,
    externalId: "NSH-GTC3",
    categoryId: categoryIds.shoes,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Nike GT Cut 3",
    description: "Responsive basketball shoes for fast court movement.",
    brand: "Nike",
    basePrice: 195,
    currency: "SGD",
    imageUrl: null,
    attributes: {
      productType: "basketball_shoes",
      sport: "basketball",
      material: "Mesh and synthetic overlays",
      deliveryZone: "NUS campus",
    },
    active: true,
  },
  {
    id: productIds.kentRidgeGtCut3,
    merchantId: merchantIds.kentRidgeSports,
    externalId: "KRS-GTC3",
    categoryId: categoryIds.shoes,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Nike GT Cut 3",
    description: "Basketball shoes available for campus pickup.",
    brand: "Nike",
    basePrice: 195,
    currency: "SGD",
    imageUrl: null,
    attributes: {
      productType: "basketball_shoes",
      sport: "basketball",
      material: "Mesh and synthetic overlays",
      fulfilment: "campus_pickup",
    },
    active: true,
  },
  {
    id: productIds.analyticsStarterKit,
    merchantId: merchantIds.digitalLearningLab,
    externalId: "DLL-ANALYTICS-STARTER",
    categoryId: categoryIds.digitalProducts,
    productKind: ProductKind.DIGITAL_PRODUCT,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.UNLIMITED,
    name: "Data Analytics Starter Kit",
    description: "Downloadable templates, exercises, and reference notes.",
    brand: "NUS Digital Learning Lab",
    basePrice: 39,
    currency: "SGD",
    imageUrl: null,
    attributes: {
      productType: "learning_bundle",
      language: "English",
      level: "beginner",
    },
    active: true,
  },
  {
    id: productIds.careerCoaching,
    merchantId: merchantIds.careerStudio,
    externalId: "CCS-CAREER-60",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "60-Minute Career Coaching",
    description: "One-to-one CV review and interview preparation session.",
    brand: "Campus Career Studio",
    basePrice: 80,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "career_coaching", language: "English" },
    active: true,
  },
  {
    id: productIds.sentosaKayaking,
    merchantId: merchantIds.lionCityExperiences,
    externalId: "LCE-SENTOSA-KAYAK",
    categoryId: categoryIds.activities,
    productKind: ProductKind.BOOKING,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.CAPACITY,
    name: "Sentosa Sunset Kayaking",
    description: "Guided small-group sunset kayaking experience.",
    brand: "Lion City Experiences",
    basePrice: 95,
    currency: "SGD",
    imageUrl: null,
    attributes: {
      experienceType: "outdoor_activity",
      destination: "Sentosa, Singapore",
      difficulty: "beginner",
      equipmentIncluded: true,
      minimumAge: 12,
    },
    active: true,
  },
  {
    id: productIds.iphone16Pro,
    merchantId: merchantIds.orchardTech,
    externalId: "OT-IP16P",
    categoryId: categoryIds.smartphones,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "iPhone 16 Pro",
    description: "Apple smartphone in multiple storage and colour variants.",
    brand: "Apple",
    basePrice: 1599,
    currency: "SGD",
    imageUrl: null,
    attributes: {
      productType: "smartphone",
      model: "iPhone 16 Pro",
      operatingSystem: "iOS",
    },
    active: true,
  },
  {
    id: productIds.gadgetHubBlender,
    merchantId: merchantIds.nusGadgetHub,
    externalId: "NGH-BLEND-900",
    categoryId: categoryIds.homeAppliances,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "SmartBlend Pro 900W Blender",
    description: "High-torque countertop blender for smoothies and meal prep.",
    brand: "SmartBlend",
    basePrice: 89,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "blender" },
    active: true,
  },
  {
    id: productIds.gadgetHubEarbuds,
    merchantId: merchantIds.nusGadgetHub,
    externalId: "NGH-PULSEBUDS-AIR",
    categoryId: categoryIds.audio,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "PulseBuds Air",
    description: "Wireless earbuds with active noise cancellation and a 24-hour battery case.",
    brand: "PulseAudio",
    basePrice: 129,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "earbuds", noiseCancelling: true },
    active: true,
  },
  {
    id: productIds.gadgetHubLaptop,
    merchantId: merchantIds.nusGadgetHub,
    externalId: "NGH-ULTRABOOK-14",
    categoryId: categoryIds.laptops,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Gadget Hub Ultrabook 14",
    description: "14-inch everyday laptop for browsing, study, and office work.",
    brand: "Gadget Hub",
    basePrice: 899,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop", useCase: "general_productivity" },
    active: true,
  },
  {
    id: productIds.gadgetHubPowerBank,
    merchantId: merchantIds.nusGadgetHub,
    externalId: "NGH-POWERBANK-20K",
    categoryId: categoryIds.electronicsAccessories,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "FastCharge Power Bank 20000mAh",
    description: "High-capacity portable charger with fast-charging USB-C output.",
    brand: "FastCharge",
    basePrice: 45,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "power_bank", compatibility: "universal" },
    active: true,
  },
  {
    id: productIds.circuitBytePro15,
    merchantId: merchantIds.circuitAndByte,
    externalId: "CB-BYTEPRO-15",
    categoryId: categoryIds.laptops,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Byte Pro 15",
    description: "15-inch laptop with discrete graphics for light video editing and gaming.",
    brand: "Byte",
    basePrice: 1799,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop", useCase: "video_editing" },
    active: true,
  },
  {
    id: productIds.circuitBytePhoneX,
    merchantId: merchantIds.circuitAndByte,
    externalId: "CB-BYTEPHONE-X",
    categoryId: categoryIds.smartphones,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Byte Phone X",
    description: "Android smartphone with a clean feature set at a mid-range price.",
    brand: "Byte",
    basePrice: 699,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "smartphone", model: "Byte Phone X", operatingSystem: "Android" },
    active: true,
  },
  {
    id: productIds.accessoryWorldEarbuds,
    merchantId: merchantIds.accessoryWorldSg,
    externalId: "AW-SOUNDWAVE-WIRED",
    categoryId: categoryIds.audio,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "SoundWave Wired Earphones",
    description: "Budget wired earphones with an in-line microphone.",
    brand: "SoundWave",
    basePrice: 15,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "earphones", noiseCancelling: false },
    active: true,
  },
  {
    id: productIds.accessoryWorldPhoneCase,
    merchantId: merchantIds.accessoryWorldSg,
    externalId: "AW-CLEARVIEW-CASE",
    categoryId: categoryIds.electronicsAccessories,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "ClearView Phone Case",
    description: "Slim protective case compatible with iPhone 16 Pro.",
    brand: "ClearView",
    basePrice: 19,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "phone_case", compatibility: "iPhone 16 Pro" },
    active: true,
  },
  {
    id: productIds.accessoryWorldCharger,
    merchantId: merchantIds.accessoryWorldSg,
    externalId: "AW-USBC-65W",
    categoryId: categoryIds.electronicsAccessories,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "USB-C Fast Charger 65W",
    description: "Compact 65W USB-C wall charger for phones and laptops.",
    brand: "AccessoryWorld",
    basePrice: 29,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "charger", compatibility: "USB-C" },
    active: true,
  },
  {
    id: productIds.accessoryWorldLaptopSleeve,
    merchantId: merchantIds.accessoryWorldSg,
    externalId: "AW-SLEEVE-14",
    categoryId: categoryIds.electronicsAccessories,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Padded Laptop Sleeve 14-inch",
    description: "Water-resistant padded sleeve for 14-inch laptops.",
    brand: "AccessoryWorld",
    basePrice: 22,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop_sleeve", compatibility: "14-inch laptops" },
    active: true,
  },
  {
    id: productIds.creatorbook14,
    merchantId: merchantIds.campusComputeCo,
    externalId: "CCC-CREATORBOOK-14",
    categoryId: categoryIds.laptops,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "Creatorbook 14",
    description: "14-inch laptop tuned for everyday editing workloads.",
    brand: "Vantage",
    basePrice: 1499,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop", useCase: "video_editing" },
    active: true,
  },
  {
    id: productIds.studioProX,
    merchantId: merchantIds.studioHardwareSg,
    externalId: "SHS-STUDIOPRO-X",
    categoryId: categoryIds.laptops,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "StudioPro X",
    description: "16-inch workstation laptop built for video editing and 3D work.",
    brand: "Forge",
    basePrice: 2199,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop", useCase: "video_editing" },
    active: true,
  },
  {
    id: productIds.renderBookPro,
    merchantId: merchantIds.pixelWorksLabs,
    externalId: "PWL-RENDERBOOK-PRO",
    categoryId: categoryIds.laptops,
    productKind: ProductKind.PHYSICAL_GOOD,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.STOCK,
    name: "RenderBook Pro",
    // Deliberately matches StudioPro X on every dimension Step B compares
    // (spec, price) so the two form a genuine tie — the agent's tiebreak
    // path needs two offers that don't differ on anything that matters,
    // which the other, deliberately-distinct laptops never produce.
    description: "16-inch workstation laptop built for video editing and 3D rendering.",
    brand: "Pixelworks",
    basePrice: 2199,
    currency: "SGD",
    imageUrl: null,
    attributes: { productType: "laptop", useCase: "video_editing" },
    active: true,
  },
  {
    id: productIds.resumeWriting,
    merchantId: merchantIds.careerLaunchCollective,
    externalId: "CLC-RESUME-WRITING",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Resume Writing & Optimization",
    description: "Professionally rewritten resume tailored to your target role.",
    brand: "Career Launch Collective",
    basePrice: 50,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "resume_writing", language: "English" },
    active: true,
  },
  {
    id: productIds.linkedinMakeover,
    merchantId: merchantIds.careerLaunchCollective,
    externalId: "CLC-LINKEDIN-MAKEOVER",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "LinkedIn Profile Makeover",
    description: "Full rewrite and optimization of your LinkedIn profile for recruiter visibility.",
    brand: "Career Launch Collective",
    basePrice: 60,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "linkedin_optimization", language: "English" },
    active: true,
  },
  {
    id: productIds.mockInterview,
    merchantId: merchantIds.careerLaunchCollective,
    externalId: "CLC-MOCK-INTERVIEW",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Mock Interview Session",
    description: "One-on-one practice interview with structured feedback.",
    brand: "Career Launch Collective",
    basePrice: 90,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "interview_prep", language: "English" },
    active: true,
  },
  {
    id: productIds.resumeReviewPackage,
    merchantId: merchantIds.careerStudio,
    externalId: "CCS-RESUME-REVIEW",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Resume Review Package",
    description: "Line-by-line resume review and feedback session.",
    brand: "Campus Career Studio",
    basePrice: 40,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "resume_writing", language: "English" },
    active: true,
  },
  {
    id: productIds.bookkeepingMonthly,
    merchantId: merchantIds.ledgerlinePartners,
    externalId: "LLP-BOOKKEEPING-MONTHLY",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Monthly Bookkeeping Package",
    description: "Recurring transaction categorization and reconciliation for a small business.",
    brand: "Ledgerline Partners",
    basePrice: 75,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "bookkeeping", language: "English" },
    active: true,
  },
  {
    id: productIds.payrollProcessing,
    merchantId: merchantIds.adminAndBeyond,
    externalId: "ABS-PAYROLL",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Payroll Processing Add-on",
    description: "Monthly payroll processing for small teams.",
    brand: "Admin & Beyond Services",
    basePrice: 60,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "payroll_admin", language: "English" },
    active: true,
  },
  {
    id: productIds.taxFilingAssistance,
    merchantId: merchantIds.adminAndBeyond,
    externalId: "ABS-TAX-FILING",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Tax Filing Assistance",
    description: "Individual or small-business tax filing support.",
    brand: "Admin & Beyond Services",
    basePrice: 120,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "tax_filing", language: "English" },
    active: true,
  },
  {
    id: productIds.notarizationService,
    merchantId: merchantIds.adminAndBeyond,
    externalId: "ABS-NOTARIZATION",
    categoryId: categoryIds.professionalServices,
    productKind: ProductKind.SERVICE,
    billingModel: BillingModel.ONE_TIME,
    availabilityModel: AvailabilityModel.TIME_SLOT,
    name: "Notarization Service",
    description: "Document notarization by appointment.",
    brand: "Admin & Beyond Services",
    basePrice: 25,
    currency: "SGD",
    imageUrl: null,
    attributes: { serviceType: "notarization", language: "English" },
    active: true,
  },
];

const physicalGoodDetails: Prisma.PhysicalGoodDetailsCreateManyInput[] = [
  {
    productId: productIds.sneakerHubGtCut3,
    weightGrams: 390,
    lengthCm: 32,
    widthCm: 21,
    heightCm: 12,
    shippingRequired: true,
  },
  {
    productId: productIds.kentRidgeGtCut3,
    weightGrams: 390,
    lengthCm: 32,
    widthCm: 21,
    heightCm: 12,
    shippingRequired: false,
  },
  {
    productId: productIds.iphone16Pro,
    weightGrams: 199,
    lengthCm: 14.96,
    widthCm: 7.15,
    heightCm: 0.83,
    shippingRequired: true,
  },
  {
    productId: productIds.gadgetHubBlender,
    weightGrams: 2200,
    lengthCm: 20,
    widthCm: 18,
    heightCm: 40,
    shippingRequired: true,
  },
  {
    productId: productIds.gadgetHubEarbuds,
    weightGrams: 55,
    lengthCm: 6,
    widthCm: 6,
    heightCm: 3,
    shippingRequired: true,
  },
  {
    productId: productIds.gadgetHubLaptop,
    weightGrams: 1400,
    lengthCm: 32,
    widthCm: 22,
    heightCm: 2,
    shippingRequired: true,
  },
  {
    productId: productIds.gadgetHubPowerBank,
    weightGrams: 400,
    lengthCm: 15,
    widthCm: 7,
    heightCm: 2.5,
    shippingRequired: true,
  },
  {
    productId: productIds.circuitBytePro15,
    weightGrams: 1900,
    lengthCm: 35,
    widthCm: 24,
    heightCm: 2.2,
    shippingRequired: true,
  },
  {
    productId: productIds.circuitBytePhoneX,
    weightGrams: 190,
    lengthCm: 15,
    widthCm: 7.2,
    heightCm: 0.8,
    shippingRequired: true,
  },
  {
    productId: productIds.accessoryWorldEarbuds,
    weightGrams: 30,
    lengthCm: 5,
    widthCm: 5,
    heightCm: 3,
    shippingRequired: true,
  },
  {
    productId: productIds.accessoryWorldPhoneCase,
    weightGrams: 40,
    lengthCm: 15,
    widthCm: 7.5,
    heightCm: 1,
    shippingRequired: true,
  },
  {
    productId: productIds.accessoryWorldCharger,
    weightGrams: 120,
    lengthCm: 6,
    widthCm: 6,
    heightCm: 3,
    shippingRequired: true,
  },
  {
    productId: productIds.accessoryWorldLaptopSleeve,
    weightGrams: 200,
    lengthCm: 36,
    widthCm: 26,
    heightCm: 2,
    shippingRequired: true,
  },
  {
    productId: productIds.creatorbook14,
    weightGrams: 1500,
    lengthCm: 32,
    widthCm: 22,
    heightCm: 1.8,
    shippingRequired: true,
  },
  {
    productId: productIds.studioProX,
    weightGrams: 2200,
    lengthCm: 36,
    widthCm: 25,
    heightCm: 2.2,
    shippingRequired: true,
  },
  {
    productId: productIds.renderBookPro,
    weightGrams: 2200,
    lengthCm: 36,
    widthCm: 25,
    heightCm: 2.2,
    shippingRequired: true,
  },
];

const digitalProductDetails: Prisma.DigitalProductDetailsCreateManyInput[] = [
  {
    productId: productIds.analyticsStarterKit,
    deliveryMethod: DigitalDeliveryMethod.DOWNLOAD,
    fileFormat: "ZIP/PDF/XLSX",
    fileSizeBytes: 52_428_800n,
    version: "2026.1",
    licenseRequired: true,
    accessDurationDays: 365,
    fulfillmentUrl: "https://example.com/demo/data-analytics-starter-kit",
  },
];

const serviceDetails: Prisma.ServiceDetailsCreateManyInput[] = [
  {
    productId: productIds.careerCoaching,
    serviceType: "career_coaching",
    deliveryMode: ServiceDeliveryMode.HYBRID,
    durationMinutes: 60,
    location: "NUS Central Library or remote video call",
    serviceAreas: ["NUS Kent Ridge", "Remote"],
    providerName: "Campus Career Studio Coach",
    bookingRequired: true,
  },
  {
    productId: productIds.resumeWriting,
    serviceType: "resume_writing",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 30,
    location: "Remote",
    serviceAreas: ["Remote"],
    providerName: "Career Launch Collective Writer",
    bookingRequired: true,
  },
  {
    productId: productIds.linkedinMakeover,
    serviceType: "linkedin_optimization",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 45,
    location: "Remote",
    serviceAreas: ["Remote"],
    providerName: "Career Launch Collective Consultant",
    bookingRequired: true,
  },
  {
    productId: productIds.mockInterview,
    serviceType: "interview_prep",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 60,
    location: "Remote video call",
    serviceAreas: ["Remote"],
    providerName: "Career Launch Collective Coach",
    bookingRequired: true,
  },
  {
    productId: productIds.resumeReviewPackage,
    serviceType: "resume_writing",
    deliveryMode: ServiceDeliveryMode.HYBRID,
    durationMinutes: 30,
    location: "NUS Central Library or remote video call",
    serviceAreas: ["NUS Kent Ridge", "Remote"],
    providerName: "Campus Career Studio Coach",
    bookingRequired: true,
  },
  {
    productId: productIds.bookkeepingMonthly,
    serviceType: "bookkeeping",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 45,
    location: "Remote video call",
    serviceAreas: ["Remote"],
    providerName: "Ledgerline Partners Bookkeeper",
    bookingRequired: true,
  },
  {
    productId: productIds.payrollProcessing,
    serviceType: "payroll_admin",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 30,
    location: "Remote",
    serviceAreas: ["Remote"],
    providerName: "Admin & Beyond Services Coordinator",
    bookingRequired: true,
  },
  {
    productId: productIds.taxFilingAssistance,
    serviceType: "tax_filing",
    deliveryMode: ServiceDeliveryMode.REMOTE,
    durationMinutes: 60,
    location: "Remote",
    serviceAreas: ["Remote"],
    providerName: "Admin & Beyond Services Tax Preparer",
    bookingRequired: true,
  },
  {
    productId: productIds.notarizationService,
    serviceType: "notarization",
    deliveryMode: ServiceDeliveryMode.HYBRID,
    durationMinutes: 20,
    location: "NUS campus or remote video call",
    serviceAreas: ["NUS Kent Ridge", "Remote"],
    providerName: "Admin & Beyond Services Notary",
    bookingRequired: true,
  },
];

const bookingExperienceDetails: Prisma.BookingExperienceDetailsCreateManyInput[] =
  [
    {
      productId: productIds.sentosaKayaking,
      experienceType: "outdoor_activity",
      destination: "Sentosa, Singapore",
      venue: "Siloso Beach",
      startsAt: new Date("2026-09-05T17:30:00+08:00"),
      endsAt: new Date("2026-09-05T19:30:00+08:00"),
      timezone: "Asia/Singapore",
      capacity: 12,
      minParticipants: 2,
      meetingPoint: "Siloso Point ticketing kiosk",
    },
  ];

const variants: Prisma.ProductVariantCreateManyInput[] = [
  {
    id: "b1111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.sneakerHub,
    productId: productIds.sneakerHubGtCut3,
    externalId: "NSH-GTC3-US8-BLK",
    sku: "NSH-GTC3-US8-BLK",
    name: "US 8 / Black",
    attributes: { size: "US 8", color: "Black" },
    listedPrice: 195,
    active: true,
  },
  {
    id: "b1111111-1111-4111-8111-111111111112",
    merchantId: merchantIds.sneakerHub,
    productId: productIds.sneakerHubGtCut3,
    externalId: "NSH-GTC3-US9-BLK",
    sku: "NSH-GTC3-US9-BLK",
    name: "US 9 / Black",
    attributes: { size: "US 9", color: "Black" },
    listedPrice: 195,
    active: true,
  },
  {
    id: "b1111111-1111-4111-8111-111111111113",
    merchantId: merchantIds.sneakerHub,
    productId: productIds.sneakerHubGtCut3,
    externalId: "NSH-GTC3-US10-BLK",
    sku: "NSH-GTC3-US10-BLK",
    name: "US 10 / Black",
    attributes: { size: "US 10", color: "Black" },
    listedPrice: 195,
    active: true,
  },
  {
    id: "b2222222-2222-4222-8222-222222222221",
    merchantId: merchantIds.kentRidgeSports,
    productId: productIds.kentRidgeGtCut3,
    externalId: "KRS-GTC3-US9-BLK",
    sku: "KRS-GTC3-US9-BLK",
    name: "US 9 / Black",
    attributes: { size: "US 9", color: "Black" },
    listedPrice: 195,
    active: true,
  },
  {
    id: "b2222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.kentRidgeSports,
    productId: productIds.kentRidgeGtCut3,
    externalId: "KRS-GTC3-US10-BLK",
    sku: "KRS-GTC3-US10-BLK",
    name: "US 10 / Black",
    attributes: { size: "US 10", color: "Black" },
    listedPrice: 195,
    active: true,
  },
  {
    id: "b3333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.digitalLearningLab,
    productId: productIds.analyticsStarterKit,
    externalId: "DLL-ANALYTICS-INDIVIDUAL",
    sku: "DLL-ANALYTICS-INDIVIDUAL",
    name: "Individual licence",
    attributes: { license: "individual" },
    listedPrice: 39,
    active: true,
  },
  {
    id: "b4444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.careerStudio,
    productId: productIds.careerCoaching,
    externalId: "CCS-CAREER-HYBRID-60",
    sku: "CCS-CAREER-HYBRID-60",
    name: "Hybrid / 60 minutes",
    attributes: { mode: "hybrid", durationMinutes: 60 },
    listedPrice: 80,
    active: true,
  },
  {
    id: "b5555555-5555-4555-8555-555555555555",
    merchantId: merchantIds.lionCityExperiences,
    productId: productIds.sentosaKayaking,
    externalId: "LCE-KAYAK-20260905-1730",
    sku: "LCE-KAYAK-20260905-1730",
    name: "5 Sep 2026 / 17:30",
    attributes: { date: "2026-09-05", time: "17:30" },
    listedPrice: 95,
    active: true,
  },
  {
    id: "b6666666-6666-4666-8666-666666666661",
    merchantId: merchantIds.orchardTech,
    productId: productIds.iphone16Pro,
    externalId: "OT-IP16P-128-BLK",
    sku: "OT-IP16P-128-BLK",
    name: "128GB / Black",
    attributes: { storage: "128GB", color: "Black" },
    listedPrice: 1599,
    active: true,
  },
  {
    id: "b6666666-6666-4666-8666-666666666662",
    merchantId: merchantIds.orchardTech,
    productId: productIds.iphone16Pro,
    externalId: "OT-IP16P-256-BLK",
    sku: "OT-IP16P-256-BLK",
    name: "256GB / Black",
    attributes: { storage: "256GB", color: "Black" },
    listedPrice: 1749,
    active: true,
  },
  {
    id: "b6666666-6666-4666-8666-666666666663",
    merchantId: merchantIds.orchardTech,
    productId: productIds.iphone16Pro,
    externalId: "OT-IP16P-256-WHT",
    sku: "OT-IP16P-256-WHT",
    name: "256GB / White",
    attributes: { storage: "256GB", color: "White" },
    listedPrice: 1749,
    active: true,
  },
  {
    id: "bb111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubBlender,
    externalId: "NGH-BLEND-900-SLV",
    sku: "NGH-BLEND-900-SLV",
    name: "Silver",
    attributes: { wattage: 900, color: "Silver" },
    listedPrice: 89,
    active: true,
  },
  {
    id: "bb222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubEarbuds,
    externalId: "NGH-PULSEBUDS-AIR-BLK",
    sku: "NGH-PULSEBUDS-AIR-BLK",
    name: "Black",
    attributes: { batteryLifeHours: 24, color: "Black" },
    listedPrice: 129,
    active: true,
  },
  {
    id: "bb333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubLaptop,
    externalId: "NGH-ULTRABOOK-14-8-256",
    sku: "NGH-ULTRABOOK-14-8-256",
    name: "8GB RAM / 256GB SSD / integrated GPU",
    attributes: { gpu: "integrated", ramGb: 8, storageGb: 256 },
    listedPrice: 899,
    active: true,
  },
  {
    id: "bb444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubPowerBank,
    externalId: "NGH-POWERBANK-20K-BLK",
    sku: "NGH-POWERBANK-20K-BLK",
    name: "Black",
    attributes: { color: "Black" },
    listedPrice: 45,
    active: true,
  },
  {
    id: "cc111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.circuitAndByte,
    productId: productIds.circuitBytePro15,
    externalId: "CB-BYTEPRO-15-16-512-RTX",
    sku: "CB-BYTEPRO-15-16-512-RTX",
    name: "16GB RAM / 512GB SSD / RTX-class GPU",
    attributes: { gpu: "RTX-class discrete", ramGb: 16, storageGb: 512 },
    listedPrice: 1799,
    active: true,
  },
  {
    id: "cc222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.circuitAndByte,
    productId: productIds.circuitBytePhoneX,
    externalId: "CB-BYTEPHONE-X-128-BLK",
    sku: "CB-BYTEPHONE-X-128-BLK",
    name: "128GB / Black",
    attributes: { storage: "128GB", color: "Black" },
    listedPrice: 699,
    active: true,
  },
  {
    id: "dd111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldEarbuds,
    externalId: "AW-SOUNDWAVE-WIRED-BLK",
    sku: "AW-SOUNDWAVE-WIRED-BLK",
    name: "Black",
    attributes: { color: "Black" },
    listedPrice: 15,
    active: true,
  },
  {
    id: "dd222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldPhoneCase,
    externalId: "AW-CLEARVIEW-CASE-CLR",
    sku: "AW-CLEARVIEW-CASE-CLR",
    name: "Clear",
    attributes: { color: "Clear" },
    listedPrice: 19,
    active: true,
  },
  {
    id: "dd333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldCharger,
    externalId: "AW-USBC-65W-WHT",
    sku: "AW-USBC-65W-WHT",
    name: "White",
    attributes: { color: "White" },
    listedPrice: 29,
    active: true,
  },
  {
    id: "dd444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldLaptopSleeve,
    externalId: "AW-SLEEVE-14-GRY",
    sku: "AW-SLEEVE-14-GRY",
    name: "Grey",
    attributes: { color: "Grey" },
    listedPrice: 22,
    active: true,
  },
  {
    id: "c7777777-7777-4777-8777-777777777771",
    merchantId: merchantIds.campusComputeCo,
    productId: productIds.creatorbook14,
    externalId: "CCC-CREATORBOOK-14-16-512",
    sku: "CCC-CREATORBOOK-14-16-512",
    name: "16GB RAM / 512GB SSD / integrated GPU",
    attributes: { gpu: "integrated", ramGb: 16, storageGb: 512 },
    listedPrice: 1499,
    active: true,
  },
  {
    id: "c8888888-8888-4888-8888-888888888881",
    merchantId: merchantIds.studioHardwareSg,
    productId: productIds.studioProX,
    externalId: "SHS-STUDIOPRO-X-32-1TB-RTX",
    sku: "SHS-STUDIOPRO-X-32-1TB-RTX",
    name: "32GB RAM / 1TB SSD / RTX-class GPU",
    attributes: { gpu: "RTX-class discrete", ramGb: 32, storageGb: 1000 },
    listedPrice: 2199,
    active: true,
  },
  {
    id: "caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    merchantId: merchantIds.pixelWorksLabs,
    productId: productIds.renderBookPro,
    externalId: "PWL-RENDERBOOK-PRO-32-1TB-RTX",
    sku: "PWL-RENDERBOOK-PRO-32-1TB-RTX",
    name: "32GB RAM / 1TB SSD / RTX-class GPU",
    attributes: { gpu: "RTX-class discrete", ramGb: 32, storageGb: 1000 },
    listedPrice: 2199,
    active: true,
  },
  {
    id: "ee111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.resumeWriting,
    externalId: "CLC-RESUME-WRITING-STD",
    sku: "CLC-RESUME-WRITING-STD",
    name: "Standard package",
    attributes: { mode: "remote", durationMinutes: 30 },
    listedPrice: 50,
    active: true,
  },
  {
    id: "ee222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.linkedinMakeover,
    externalId: "CLC-LINKEDIN-MAKEOVER-STD",
    sku: "CLC-LINKEDIN-MAKEOVER-STD",
    name: "Standard package",
    attributes: { mode: "remote", durationMinutes: 45 },
    listedPrice: 60,
    active: true,
  },
  {
    id: "ee333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.mockInterview,
    externalId: "CLC-MOCK-INTERVIEW-STD",
    sku: "CLC-MOCK-INTERVIEW-STD",
    name: "Standard session",
    attributes: { mode: "remote", durationMinutes: 60 },
    listedPrice: 90,
    active: true,
  },
  {
    id: "ee444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.careerStudio,
    productId: productIds.resumeReviewPackage,
    externalId: "CCS-RESUME-REVIEW-STD",
    sku: "CCS-RESUME-REVIEW-STD",
    name: "Standard package",
    attributes: { mode: "hybrid", durationMinutes: 30 },
    listedPrice: 40,
    active: true,
  },
  {
    id: "c9999999-9999-4999-8999-999999999991",
    merchantId: merchantIds.ledgerlinePartners,
    productId: productIds.bookkeepingMonthly,
    externalId: "LLP-BOOKKEEPING-MONTHLY-STD",
    sku: "LLP-BOOKKEEPING-MONTHLY-STD",
    name: "Standard monthly package",
    attributes: { mode: "remote", durationMinutes: 45 },
    listedPrice: 75,
    active: true,
  },
  {
    id: "ff111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.payrollProcessing,
    externalId: "ABS-PAYROLL-STD",
    sku: "ABS-PAYROLL-STD",
    name: "Standard package",
    attributes: { mode: "remote", durationMinutes: 30 },
    listedPrice: 60,
    active: true,
  },
  {
    id: "ff222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.taxFilingAssistance,
    externalId: "ABS-TAX-FILING-STD",
    sku: "ABS-TAX-FILING-STD",
    name: "Standard package",
    attributes: { mode: "remote", durationMinutes: 60 },
    listedPrice: 120,
    active: true,
  },
  {
    id: "ff333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.notarizationService,
    externalId: "ABS-NOTARIZATION-STD",
    sku: "ABS-NOTARIZATION-STD",
    name: "Standard appointment",
    attributes: { mode: "hybrid", durationMinutes: 20 },
    listedPrice: 25,
    active: true,
  },
];

const inventoryQuantities: Array<readonly [string, string, number]> = [
  ["b1111111-1111-4111-8111-111111111111", merchantIds.sneakerHub, 5],
  ["b1111111-1111-4111-8111-111111111112", merchantIds.sneakerHub, 2],
  ["b1111111-1111-4111-8111-111111111113", merchantIds.sneakerHub, 7],
  ["b2222222-2222-4222-8222-222222222221", merchantIds.kentRidgeSports, 25],
  ["b2222222-2222-4222-8222-222222222222", merchantIds.kentRidgeSports, 4],
  [
    "b3333333-3333-4333-8333-333333333333",
    merchantIds.digitalLearningLab,
    1000,
  ],
  ["b4444444-4444-4444-8444-444444444444", merchantIds.careerStudio, 8],
  ["b5555555-5555-4555-8555-555555555555", merchantIds.lionCityExperiences, 12],
  ["b6666666-6666-4666-8666-666666666661", merchantIds.orchardTech, 8],
  ["b6666666-6666-4666-8666-666666666662", merchantIds.orchardTech, 12],
  ["b6666666-6666-4666-8666-666666666663", merchantIds.orchardTech, 6],
  ["bb111111-1111-4111-8111-111111111111", merchantIds.nusGadgetHub, 15],
  ["bb222222-2222-4222-8222-222222222222", merchantIds.nusGadgetHub, 20],
  ["bb333333-3333-4333-8333-333333333333", merchantIds.nusGadgetHub, 10],
  ["bb444444-4444-4444-8444-444444444444", merchantIds.nusGadgetHub, 30],
  ["cc111111-1111-4111-8111-111111111111", merchantIds.circuitAndByte, 9],
  ["cc222222-2222-4222-8222-222222222222", merchantIds.circuitAndByte, 14],
  ["dd111111-1111-4111-8111-111111111111", merchantIds.accessoryWorldSg, 40],
  ["dd222222-2222-4222-8222-222222222222", merchantIds.accessoryWorldSg, 50],
  ["dd333333-3333-4333-8333-333333333333", merchantIds.accessoryWorldSg, 35],
  ["dd444444-4444-4444-8444-444444444444", merchantIds.accessoryWorldSg, 25],
  ["c7777777-7777-4777-8777-777777777771", merchantIds.campusComputeCo, 10],
  ["c8888888-8888-4888-8888-888888888881", merchantIds.studioHardwareSg, 6],
  ["caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", merchantIds.pixelWorksLabs, 6],
  ["ee111111-1111-4111-8111-111111111111", merchantIds.careerLaunchCollective, 20],
  ["ee222222-2222-4222-8222-222222222222", merchantIds.careerLaunchCollective, 20],
  ["ee333333-3333-4333-8333-333333333333", merchantIds.careerLaunchCollective, 20],
  ["ee444444-4444-4444-8444-444444444444", merchantIds.careerStudio, 15],
  ["c9999999-9999-4999-8999-999999999991", merchantIds.ledgerlinePartners, 20],
  ["ff111111-1111-4111-8111-111111111111", merchantIds.adminAndBeyond, 20],
  ["ff222222-2222-4222-8222-222222222222", merchantIds.adminAndBeyond, 20],
  ["ff333333-3333-4333-8333-333333333333", merchantIds.adminAndBeyond, 20],
];

const inventory: Prisma.InventoryCreateManyInput[] = inventoryQuantities.map(
  ([variantId, merchantId, quantityAvailable]) => ({
    id: variantId,
    merchantId,
    variantId,
    quantityAvailable,
    quantityReserved: 0,
    availability:
      quantityAvailable <= 5
        ? InventoryAvailability.LOW_STOCK
        : InventoryAvailability.IN_STOCK,
  }),
);

const pricingPolicies: Prisma.PricingPolicyCreateManyInput[] = [
  {
    id: "c1111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.sneakerHub,
    productId: productIds.sneakerHubGtCut3,
    negotiationEnabled: true,
    minimumPrice: 190,
    maxDiscountPercent: 15.38,
    inventoryDiscountEnabled: true,
    rules: { strategy: "inventory_aware" },
  },
  {
    id: "c2222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.kentRidgeSports,
    productId: productIds.kentRidgeGtCut3,
    negotiationEnabled: true,
    minimumPrice: 165,
    maxDiscountPercent: 15.38,
    inventoryDiscountEnabled: true,
    rules: { strategy: "bounded_discount" },
  },
  {
    id: "c3333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.digitalLearningLab,
    productId: productIds.analyticsStarterKit,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "c4444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.careerStudio,
    productId: productIds.careerCoaching,
    negotiationEnabled: true,
    minimumPrice: 70,
    maxDiscountPercent: 12.5,
    inventoryDiscountEnabled: false,
    rules: { strategy: "bounded_discount" },
  },
  {
    id: "c5555555-5555-4555-8555-555555555555",
    merchantId: merchantIds.lionCityExperiences,
    productId: productIds.sentosaKayaking,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "c6666666-6666-4666-8666-666666666666",
    merchantId: merchantIds.orchardTech,
    productId: productIds.iphone16Pro,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cb111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubBlender,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cb222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubEarbuds,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cb333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubLaptop,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cb444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.nusGadgetHub,
    productId: productIds.gadgetHubPowerBank,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cc111111-1111-4111-8888-111111111111",
    merchantId: merchantIds.circuitAndByte,
    productId: productIds.circuitBytePro15,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cc222222-2222-4888-8888-222222222222",
    merchantId: merchantIds.circuitAndByte,
    productId: productIds.circuitBytePhoneX,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cd111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldEarbuds,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cd222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldPhoneCase,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cd333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldCharger,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cd444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.accessoryWorldSg,
    productId: productIds.accessoryWorldLaptopSleeve,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "e7777777-7777-4777-8777-777777777771",
    merchantId: merchantIds.campusComputeCo,
    productId: productIds.creatorbook14,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "e8888888-8888-4888-8888-888888888881",
    merchantId: merchantIds.studioHardwareSg,
    productId: productIds.studioProX,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "eaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    merchantId: merchantIds.pixelWorksLabs,
    productId: productIds.renderBookPro,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "ce111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.resumeWriting,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "ce222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.linkedinMakeover,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "ce333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.careerLaunchCollective,
    productId: productIds.mockInterview,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "ce444444-4444-4444-8444-444444444444",
    merchantId: merchantIds.careerStudio,
    productId: productIds.resumeReviewPackage,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "e9999999-9999-4999-8999-999999999991",
    merchantId: merchantIds.ledgerlinePartners,
    productId: productIds.bookkeepingMonthly,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cf111111-1111-4111-8111-111111111111",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.payrollProcessing,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cf222222-2222-4222-8222-222222222222",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.taxFilingAssistance,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
  {
    id: "cf333333-3333-4333-8333-333333333333",
    merchantId: merchantIds.adminAndBeyond,
    productId: productIds.notarizationService,
    negotiationEnabled: false,
    minimumPrice: null,
    maxDiscountPercent: null,
    inventoryDiscountEnabled: false,
    rules: { strategy: "fixed_price" },
  },
];

const importProfiles: Prisma.MerchantImportProfileCreateManyInput[] = [
  {
    id: "f6666666-6666-4666-8666-666666666666",
    merchantId: merchantIds.orchardTech,
    categoryId: categoryIds.smartphones,
    name: "Orchard Tech smartphone CSV",
    schemaVersion: "1.0",
    sourceHeaders: [
      "item_title",
      "unit_price_sgd",
      "item_type",
      "model_name",
      "capacity",
      "color_name",
      "stock_on_hand",
      "merchant_sku",
    ],
    columnMapping: {
      item_title: "product.name",
      unit_price_sgd: "variant.listedPrice",
      item_type: "product.attributes.productType",
      model_name: "product.attributes.model",
      capacity: "variant.attributes.storage",
      color_name: "variant.attributes.color",
      stock_on_hand: "inventory.quantityAvailable",
      merchant_sku: "variant.sku",
    },
    normalizationRules: {
      capacity: { canonicalKey: "storage", trim: true, uppercaseUnit: true },
      color_name: { canonicalKey: "color", trim: true },
    },
    active: true,
  },
];

const demoUserId = "643f3382-40b2-4343-b4bf-4d62d51da5fb";

const paymentMethods: Prisma.PaymentMethodCreateManyInput[] = [
  {
    id: "e1111111-1111-4111-8111-111111111111",
    userId: demoUserId,
    provider: "Visa",
    providerCredentialRef: "vault_mock_visa_authorized",
    label: "Visa ending 4242",
    cardBrand: "Visa",
    lastFour: "4242",
    expiryMonth: 12,
    expiryYear: 2030,
    cardholderVerified: true,
    isDefault: true,
    active: true,
  },
  {
    id: "e2222222-2222-4222-8222-222222222222",
    userId: demoUserId,
    provider: "Visa",
    providerCredentialRef: "vault_mock_visa_declined",
    label: "Visa decline scenario",
    cardBrand: "Visa",
    lastFour: "0002",
    expiryMonth: 12,
    expiryYear: 2030,
    cardholderVerified: true,
    isDefault: false,
    active: true,
  },
  {
    id: "e3333333-3333-4333-8333-333333333333",
    userId: demoUserId,
    provider: "Visa",
    providerCredentialRef: "vault_mock_visa_verification",
    label: "Visa verification scenario",
    cardBrand: "Visa",
    lastFour: "0003",
    expiryMonth: 12,
    expiryYear: 2030,
    cardholderVerified: false,
    isDefault: false,
    active: true,
  },
  {
    id: "e4444444-4444-4444-8444-444444444444",
    userId: demoUserId,
    provider: "Visa",
    providerCredentialRef: "vault_mock_visa_failed",
    label: "Visa failure scenario",
    cardBrand: "Visa",
    lastFour: "0004",
    expiryMonth: 12,
    expiryYear: 2030,
    cardholderVerified: false,
    isDefault: false,
    active: true,
  },
];

async function main(): Promise<void> {
  const prisma = getPrismaClient();

  try {
    const result = await prisma.$transaction(async (transaction) => {
      for (const category of categories) {
        const { id, ...data } = category;
        await transaction.category.upsert({
          where: { id },
          create: category,
          update: data,
        });
      }
      for (const schema of categorySchemas) {
        const { id: _id, categoryId, version, ...data } = schema;
        await transaction.categorySchema.upsert({
          where: { categoryId_version: { categoryId, version } },
          create: schema,
          update: data,
        });
      }
      for (const merchant of merchants) {
        const { id, ...data } = merchant;
        await transaction.merchant.upsert({
          where: { id },
          create: merchant,
          update: data,
        });
      }
      for (const product of products) {
        const { id, ...data } = product;
        await transaction.product.upsert({
          where: { id },
          create: product,
          update: data,
        });
      }
      for (const details of physicalGoodDetails) {
        const { productId, ...data } = details;
        await transaction.physicalGoodDetails.upsert({
          where: { productId },
          create: details,
          update: data,
        });
      }
      for (const details of digitalProductDetails) {
        const { productId, ...data } = details;
        await transaction.digitalProductDetails.upsert({
          where: { productId },
          create: details,
          update: data,
        });
      }
      for (const details of serviceDetails) {
        const { productId, ...data } = details;
        await transaction.serviceDetails.upsert({
          where: { productId },
          create: details,
          update: data,
        });
      }
      for (const details of bookingExperienceDetails) {
        const { productId, ...data } = details;
        await transaction.bookingExperienceDetails.upsert({
          where: { productId },
          create: details,
          update: data,
        });
      }
      for (const variant of variants) {
        const { id, ...data } = variant;
        await transaction.productVariant.upsert({
          where: { id },
          create: variant,
          update: data,
        });
      }
      for (const inventoryItem of inventory) {
        const { id: _id, variantId, ...data } = inventoryItem;
        await transaction.inventory.upsert({
          where: { variantId },
          create: inventoryItem,
          update: data,
        });
      }
      for (const policy of pricingPolicies) {
        const { id: _id, productId, ...data } = policy;
        await transaction.pricingPolicy.upsert({
          where: { productId },
          create: policy,
          update: data,
        });
      }
      for (const profile of importProfiles) {
        const { id: _id, merchantId, name, ...data } = profile;
        await transaction.merchantImportProfile.upsert({
          where: { merchantId_name: { merchantId, name } },
          create: profile,
          update: data,
        });
      }
      for (const paymentMethod of paymentMethods) {
        const { id, ...data } = paymentMethod;
        await transaction.paymentMethod.upsert({
          where: { id },
          create: paymentMethod,
          update: data,
        });
      }

      return {
        categories: await transaction.category.count({
          where: { id: { in: categories.map(({ id }) => id as string) } },
        }),
        merchants: await transaction.merchant.count({
          where: { id: { in: merchants.map(({ id }) => id as string) } },
        }),
        products: await transaction.product.count({
          where: { id: { in: products.map(({ id }) => id as string) } },
        }),
        variants: await transaction.productVariant.count({
          where: { id: { in: variants.map(({ id }) => id as string) } },
        }),
        inventory: await transaction.inventory.count({
          where: { id: { in: inventory.map(({ id }) => id as string) } },
        }),
        paymentMethods: await transaction.paymentMethod.count({
          where: {
            id: { in: paymentMethods.map(({ id }) => id as string) },
          },
        }),
      };
    });

    console.log(
      `Seeded ${result.categories} categories, ${result.merchants} merchants, ` +
        `${result.products} products, ${result.variants} variants, ${result.inventory} inventory records, ` +
        `and ${result.paymentMethods} saved payment methods.`,
    );
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
