import {
  checkInventory,
  configurePricingPolicy,
  createMerchant,
  createOrder,
  createProduct,
  getCategorySchema,
  getPaymentStatus,
  getPricingPolicy,
  getPublicProduct,
  initiatePayment,
  listMerchants,
  listMerchantProducts,
  listCategories,
  listImportProfiles,
  requestOffers,
  saveImportProfile,
  searchProducts,
  updateProduct,
  updateProductVariant,
  upsertInventory,
} from "@visa-commerce/commerce";

export const defaultCommerceApiServices = {
  checkInventory,
  configurePricingPolicy,
  createMerchant,
  createOrder,
  createProduct,
  getCategorySchema,
  getPaymentStatus,
  getPricingPolicy,
  getPublicProduct,
  initiatePayment,
  listMerchants,
  listMerchantProducts,
  listCategories,
  listImportProfiles,
  requestOffers,
  saveImportProfile,
  searchProducts,
  updateProduct,
  updateProductVariant,
  upsertInventory,
};

export type CommerceApiServices = typeof defaultCommerceApiServices;
